### ISSUE TITLE
Issue: Peer-to-peer Code Review

### ISSUE THREAD

**Issue by Ntwali-Josue** [mateo951/js_capstone_m2#22]
Hi @mateo951 @fortuneonyeka,  

Good job so far! 💯 
However, Since we are required to use semantic HTML tags, you can try to wrap your header section in a nav tag.

**Comment by mateo951** [comment]
Thanks for the tip man!

**Comment by Hamzaoutdoors** [comment]
# Hey Team
Good job so far 👍
